#---
# D760nT#:6bBulQ
# deployment:
#   task:
#     - export DEPLOYPATH=/home/buffalo2/public_html
#     - /bin/cp index.html $DEPLOYPATH
#     - /bin/cp -R assets $DEPLOYPATH
#     - /bin/cp -R css $DEPLOYPATH
#     - /bin/cp -R js $DEPLOYPATH
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/buffalo2/buffalochemicals.com/website_test
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH